' ============================================================================
' fieldemon_macros.bas
' Part of: fieldemon
' VBA module for Davidson Group ringing data workbook
' Provides live error checking and ring number shortcut
'
' HOW TO INSTALL:
' 1. Open your .xlsm workbook in Excel
' 2. Press Alt+F11 to open the VBA editor
' 3. In the Project panel, find your workbook and expand it
' 4. Right-click on "Microsoft Excel Objects" > "ThisWorkbook"
'    and paste the Workbook_Open code there
' 5. Right-click on the sheet named "Ringing data" in the Project panel
'    and paste the Worksheet_Change code there
' 6. Right-click on "Modules" > "Insert" > "Module"
'    and paste everything else into that module
' 7. Close the VBA editor and save the workbook as .xlsm
'
' SHEETS REQUIRED:
'   "Ringing data"  - main data entry sheet
'   "Individuals"   - generated by build_individuals_table.py
'   "Species list"  - manually maintained (see setup instructions below)
'
' SPECIES LIST SHEET SETUP:
'   Create a sheet called "Species list" with these columns:
'   A: species code (e.g. BLUTI)
'   B: common name (e.g. blue tit)
'   C: ring size (e.g. A)
'   D: min wing (e.g. 58)
'   E: max wing (e.g. 68)
'   F: min weight (e.g. 8)
'   G: max weight (e.g. 12)
'   Row 1 = headers, data starts row 2
'
'   Starter data (copy into the sheet):
'   Code    Name                        Ring  MinW  MaxW  MinWt MaxWt
'   BLUTI   blue tit                    A     58    68    8     12
'   GRETI   great tit                   A     69    81    14.5  21
'   ROBIN   robin                       A     68    79    13    24
'   LOTTI   long-tailed tit             AA    56    64    6     9
'   COATI   coal tit                    A     56    64    7     10
'   DUNNO   dunnock                     B     64    75    16    25
'   NUTHA   nuthatch                    B     78    89    18    25
'   GRSWO   great spotted woodpecker    C     125   139   66    90
'   CHAFF   chaffinch                   A     75    94    16    26
'   GOLDF   goldfinch                   A     72    84    12    18
'   BLACA   blackcap                    A     69    79    13    22
'   BLABI   blackbird                   C     119   141   74    129
'   BULLF   bullfinch                   A     76    87    18    26
'   MARTI   marsh tit                   A     57    67    9     12
'   WREN    wren                        AA    43    54    7     12
'   CHIFF   chiffchaff                  AA    51    67    5     9
'   GOLDC   goldcrest                   AA    48    57    4     6
'   TREEC   treecreeper                 AA    57    68    6     10
'   REDWI   redwing                     CC    110   130   48    90
'   SONTH   song thrush                 CC    111   127   55    93
'   GARWA   garden warbler              A     68    78    12    22
'   REDPO   redpoll                     A     68    78    10    18
' ============================================================================

' ── Column constants (1-based) ───────────────────────────────────────────────
' Update these if column order changes in the Ringing data sheet
Public Const COL_LOCATION       As Integer = 1
Public Const COL_DATE           As Integer = 2
Public Const COL_SPECIES        As Integer = 3
Public Const COL_RINGNO         As Integer = 4
Public Const COL_RINGTYPE       As Integer = 5
Public Const COL_AGE            As Integer = 6
Public Const COL_SEX            As Integer = 7
Public Const COL_SEXMETHOD      As Integer = 8
Public Const COL_WING           As Integer = 9
Public Const COL_WEIGHT         As Integer = 10
Public Const COL_FECAL          As Integer = 11
Public Const COL_TIME           As Integer = 12
Public Const COL_INITIALS       As Integer = 13
Public Const COL_PITTAG         As Integer = 14
Public Const COL_PITTYPE        As Integer = 15
Public Const COL_COMMENT        As Integer = 16
Public Const COL_NESTBOX        As Integer = 17
Public Const COL_FEATHER        As Integer = 18
Public Const COL_BROOD          As Integer = 19
Public Const COL_NESTLINGAGE    As Integer = 20
Public Const COL_LETTERID       As Integer = 21
Public Const COL_FATMUSC        As Integer = 22
Public Const COL_UPLOAD         As Integer = 23
Public Const COL_ERRORS         As Integer = 24

' ── Colours ──────────────────────────────────────────────────────────────────
Public Const CLR_ERROR          As Long = 16711680  ' bright red interior
Public Const CLR_ERROR_FONT     As Long = 16777215  ' white font on red
Public Const CLR_WARN           As Long = 49407     ' orange — soft warning
Public Const CLR_WARN_FONT      As Long = 0         ' black font on orange
Public Const CLR_OK             As Long = xlNone    ' no fill = clear

' ── Sheet names ──────────────────────────────────────────────────────────────
Public Const SHT_DATA           As String = "Ringing data"
Public Const SHT_INDIVIDUALS    As String = "Individuals"
Public Const SHT_SPECIES        As String = "Species list"

' ── Individuals table column constants (1-based) ─────────────────────────────
' Matches the output of build_individuals_table.py
Public Const IND_RINGNO         As Integer = 1
Public Const IND_SPECIES        As Integer = 2
Public Const IND_SEX            As Integer = 3
Public Const IND_FIRST_SEEN     As Integer = 4
Public Const IND_LAST_SEEN      As Integer = 5
Public Const IND_N_RECORDS      As Integer = 6
Public Const IND_FIRST_RTYPE    As Integer = 7

' ============================================================================
' PASTE THIS SECTION INTO: ThisWorkbook
' ============================================================================
'
' Private Sub Workbook_Open()
'     ' Confirm required sheets exist on open
'     Dim missing As String
'     missing = ""
'     If Not SheetExists(SHT_INDIVIDUALS) Then
'         missing = missing & "  - " & SHT_INDIVIDUALS & vbCrLf
'     End If
'     If Not SheetExists(SHT_SPECIES) Then
'         missing = missing & "  - " & SHT_SPECIES & vbCrLf
'     End If
'     If Len(missing) > 0 Then
'         MsgBox "Fieldemon: the following sheets are missing and error " & _
'                "checking will not work correctly:" & vbCrLf & vbCrLf & _
'                missing & vbCrLf & _
'                "Run build_individuals_table.py and copy the Individuals " & _
'                "tab into this workbook, and ensure a Species list sheet " & _
'                "exists.", vbExclamation, "Fieldemon"
'     End If
' End Sub

' ============================================================================
' PASTE THIS SECTION INTO: the "Ringing data" sheet module
' ============================================================================
'
' Private Sub Worksheet_Change(ByVal Target As Range)
'     ' Only process single cell changes in data rows (row 2 onwards)
'     If Target.CountLarge > 1 Then Exit Sub
'     If Target.Row < 2 Then Exit Sub
'
'     ' Ignore changes in non-data columns
'     If Target.Column > COL_ERRORS Then Exit Sub
'
'     ' Disable events to prevent recursive calls while we update colours
'     Application.EnableEvents = False
'     On Error GoTo Cleanup
'
'     CheckRow Target.Row
'
' Cleanup:
'     Application.EnableEvents = True
' End Sub
'
' Private Sub Worksheet_SelectionChange(ByVal Target As Range)
'     ' Ring number shortcut: Ctrl+Shift+R fills next ring number
'     ' (handled via Application.OnKey in module — no code needed here)
' End Sub

' ============================================================================
' PASTE THIS SECTION INTO: a new Module (Insert > Module)
' ============================================================================

' ── Main row checker ─────────────────────────────────────────────────────────
Public Sub CheckRow(rowNum As Long)
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_DATA)

    ' Read values from the row
    Dim species     As String
    Dim ringNo      As String
    Dim ringType    As String
    Dim age         As String
    Dim sex         As String
    Dim sexMethod   As String
    Dim wing        As Variant
    Dim wt          As Variant

    species   = Trim(CStr(ws.Cells(rowNum, COL_SPECIES).Value))
    ringNo    = Trim(CStr(ws.Cells(rowNum, COL_RINGNO).Value))
    ringType  = Trim(CStr(ws.Cells(rowNum, COL_RINGTYPE).Value))
    age       = Trim(CStr(ws.Cells(rowNum, COL_AGE).Value))
    sex       = Trim(CStr(ws.Cells(rowNum, COL_SEX).Value))
    sexMethod = Trim(CStr(ws.Cells(rowNum, COL_SEXMETHOD).Value))
    wing      = ws.Cells(rowNum, COL_WING).Value
    wt        = ws.Cells(rowNum, COL_WEIGHT).Value

    ' ── 1. Species validation ────────────────────────────────────────────────
    If Len(species) > 0 Then
        If Not SpeciesExists(species) Then
            HighlightCell ws.Cells(rowNum, COL_SPECIES), True, _
                "Species code not recognised — check Species list sheet"
        Else
            ClearCell ws.Cells(rowNum, COL_SPECIES)
        End If
    Else
        ClearCell ws.Cells(rowNum, COL_SPECIES)
    End If

    ' ── 2. Wing range check ──────────────────────────────────────────────────
    If Len(species) > 0 And IsNumeric(wing) And CDbl(wing) > 0 Then
        Dim minWing As Double, maxWing As Double
        If GetWingRange(species, minWing, maxWing) Then
            If CDbl(wing) < minWing Or CDbl(wing) > maxWing Then
                HighlightCell ws.Cells(rowNum, COL_WING), True, _
                    "Wing " & wing & " outside expected range " & _
                    minWing & "-" & maxWing & " for " & species
            Else
                ClearCell ws.Cells(rowNum, COL_WING)
            End If
        Else
            ClearCell ws.Cells(rowNum, COL_WING)
        End If
    Else
        ClearCell ws.Cells(rowNum, COL_WING)
    End If

    ' ── 3. Weight range check ────────────────────────────────────────────────
    If Len(species) > 0 And IsNumeric(wt) And CDbl(wt) > 0 Then
        Dim minWt As Double, maxWt As Double
        If GetWeightRange(species, minWt, maxWt) Then
            If CDbl(wt) < minWt Or CDbl(wt) > maxWt Then
                HighlightCell ws.Cells(rowNum, COL_WEIGHT), True, _
                    "Weight " & wt & " outside expected range " & _
                    minWt & "-" & maxWt & " for " & species
            Else
                ClearCell ws.Cells(rowNum, COL_WEIGHT)
            End If
        Else
            ClearCell ws.Cells(rowNum, COL_WEIGHT)
        End If
    Else
        ClearCell ws.Cells(rowNum, COL_WEIGHT)
    End If

    ' ── 4-6. Ring number checks (only if ring number entered) ────────────────
    If Len(ringNo) > 0 And ringNo <> "None" Then

        Dim indRow As Long
        indRow = FindInIndividuals(ringNo)

        ' 4. N with prior record
        If UCase(ringType) = "N" Then
            If indRow > 0 Then
                HighlightCell ws.Cells(rowNum, COL_RINGNO), True, _
                    "ringType is N but " & ringNo & _
                    " already exists in Individuals table (row " & indRow & ")"
                HighlightCell ws.Cells(rowNum, COL_RINGTYPE), True, _
                    "ringType is N but ring already exists"
            Else
                ClearCell ws.Cells(rowNum, COL_RINGNO)
                ClearCell ws.Cells(rowNum, COL_RINGTYPE)
            End If

        ' 5. R with no prior record
        ElseIf UCase(ringType) = "R" Then
            If indRow = 0 Then
                HighlightCell ws.Cells(rowNum, COL_RINGNO), True, _
                    "ringType is R but " & ringNo & _
                    " not found in Individuals table — no prior record"
                HighlightCell ws.Cells(rowNum, COL_RINGTYPE), True, _
                    "ringType is R but no prior record found"
            Else
                ' 6. Sex conflict with Individuals table
                If Len(sex) > 0 And UCase(sexMethod) <> "G" Then
                    Dim indSex As String
                    indSex = GetIndividualSex(indRow)
                    If Len(indSex) > 0 And UCase(sex) <> UCase(indSex) Then
                        HighlightCell ws.Cells(rowNum, COL_SEX), True, _
                            "Sex " & sex & " conflicts with previous record " & _
                            "(" & indSex & ") in Individuals table"
                    Else
                        ClearCell ws.Cells(rowNum, COL_SEX)
                    End If
                End If

                ' 7. Species conflict with Individuals table
                If Len(species) > 0 Then
                    Dim indSpecies As String
                    indSpecies = GetIndividualSpecies(indRow)
                    If Len(indSpecies) > 0 And _
                       UCase(species) <> UCase(indSpecies) Then
                        HighlightCell ws.Cells(rowNum, COL_SPECIES), True, _
                            "Species " & species & " conflicts with previous " & _
                            "record (" & indSpecies & ") in Individuals table"
                    End If
                End If

                ClearCell ws.Cells(rowNum, COL_RINGNO)
                ClearCell ws.Cells(rowNum, COL_RINGTYPE)
            End If
        Else
            ClearCell ws.Cells(rowNum, COL_RINGNO)
            ClearCell ws.Cells(rowNum, COL_RINGTYPE)
        End If
    Else
        ClearCell ws.Cells(rowNum, COL_RINGNO)
        ClearCell ws.Cells(rowNum, COL_RINGTYPE)
    End If

End Sub

' ── Re-check all rows (run manually after pasting in Individuals tab) ─────────
Public Sub CheckAllRows()
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_DATA)
    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, COL_RINGNO).End(xlUp).Row

    Application.EnableEvents = False
    Application.ScreenUpdating = False

    Dim i As Long
    For i = 2 To lastRow
        CheckRow i
    Next i

    Application.EnableEvents = True
    Application.ScreenUpdating = True
    MsgBox "Check complete. " & (lastRow - 1) & " rows checked.", _
           vbInformation, "Fieldemon"
End Sub

' ── Ring number shortcut ──────────────────────────────────────────────────────
' Assign this to Ctrl+Shift+R via Tools > Macros > Options
' or call SetRingShortcut from Workbook_Open
Public Sub NextRingNumber()
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_DATA)

    ' Find the last non-empty ring number in the ringNo column
    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, COL_RINGNO).End(xlUp).Row

    Dim lastRing As String
    Dim searchRow As Long
    searchRow = lastRow

    ' Walk up to find last actual ring number (skip blanks/NOTRINGED etc.)
    Do While searchRow >= 2
        lastRing = Trim(CStr(ws.Cells(searchRow, COL_RINGNO).Value))
        If Len(lastRing) > 0 And lastRing <> "None" And _
           lastRing <> "NOTRINGED" And lastRing <> "LOST" Then
            Exit Do
        End If
        searchRow = searchRow - 1
    Loop

    If Len(lastRing) = 0 Then
        MsgBox "No previous ring number found to increment.", _
               vbInformation, "Fieldemon"
        Exit Sub
    End If

    ' Split prefix (letters) from suffix (digits)
    Dim prefix As String
    Dim suffix As String
    Dim i As Integer
    prefix = ""
    suffix = ""

    For i = 1 To Len(lastRing)
        Dim c As String
        c = Mid(lastRing, i, 1)
        If c >= "0" And c <= "9" Then
            suffix = Mid(lastRing, i)
            Exit For
        Else
            prefix = prefix & c
        End If
    Next i

    If Len(suffix) = 0 Then
        MsgBox "Could not parse ring number: " & lastRing, _
               vbExclamation, "Fieldemon"
        Exit Sub
    End If

    ' Increment suffix, preserving leading zeros and length
    Dim suffixLen As Integer
    suffixLen = Len(suffix)
    Dim nextNum As Long
    nextNum = CLng(suffix) + 1

    Dim nextSuffix As String
    nextSuffix = CStr(nextNum)

    ' Pad with leading zeros if needed
    Do While Len(nextSuffix) < suffixLen
        nextSuffix = "0" & nextSuffix
    Loop

    Dim nextRing As String
    nextRing = prefix & nextSuffix

    ' Put the next ring number in the active cell
    ActiveCell.Value = nextRing

End Sub

Public Sub SetRingShortcut()
    ' Call from Workbook_Open to register the shortcut
    Application.OnKey "^+r", "NextRingNumber"
End Sub

Public Sub ClearRingShortcut()
    ' Call from Workbook_BeforeClose to unregister
    Application.OnKey "^+r"
End Sub

' ── Lookup helpers ────────────────────────────────────────────────────────────
Private Function SpeciesExists(species As String) As Boolean
    If Not SheetExists(SHT_SPECIES) Then
        SpeciesExists = True  ' can't check — don't flag
        Exit Function
    End If
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_SPECIES)
    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row
    Dim found As Variant
    found = Application.Match(UCase(species), _
            ws.Range(ws.Cells(2, 1), ws.Cells(lastRow, 1)), 0)
    SpeciesExists = Not IsError(found)
End Function

Private Function GetWingRange(species As String, _
        ByRef minVal As Double, ByRef maxVal As Double) As Boolean
    GetWingRange = GetSpeciesRange(species, 4, 5, minVal, maxVal)
End Function

Private Function GetWeightRange(species As String, _
        ByRef minVal As Double, ByRef maxVal As Double) As Boolean
    GetWeightRange = GetSpeciesRange(species, 6, 7, minVal, maxVal)
End Function

Private Function GetSpeciesRange(species As String, _
        minCol As Integer, maxCol As Integer, _
        ByRef minVal As Double, ByRef maxVal As Double) As Boolean
    If Not SheetExists(SHT_SPECIES) Then
        GetSpeciesRange = False
        Exit Function
    End If
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_SPECIES)
    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, 1).End(xlUp).Row
    Dim found As Variant
    found = Application.Match(UCase(species), _
            ws.Range(ws.Cells(2, 1), ws.Cells(lastRow, 1)), 0)
    If IsError(found) Then
        GetSpeciesRange = False
        Exit Function
    End If
    Dim dataRow As Long
    dataRow = CLng(found) + 1  ' +1 because search started at row 2
    Dim minRaw As Variant, maxRaw As Variant
    minRaw = ws.Cells(dataRow, minCol).Value
    maxRaw = ws.Cells(dataRow, maxCol).Value
    If IsNumeric(minRaw) And IsNumeric(maxRaw) Then
        minVal = CDbl(minRaw)
        maxVal = CDbl(maxRaw)
        GetSpeciesRange = True
    Else
        GetSpeciesRange = False
    End If
End Function

Private Function FindInIndividuals(ringNo As String) As Long
    ' Returns the row number in Individuals sheet, or 0 if not found
    FindInIndividuals = 0
    If Not SheetExists(SHT_INDIVIDUALS) Then Exit Function
    Dim ws As Worksheet
    Set ws = ThisWorkbook.Sheets(SHT_INDIVIDUALS)
    Dim lastRow As Long
    lastRow = ws.Cells(ws.Rows.Count, IND_RINGNO).End(xlUp).Row
    Dim found As Variant
    found = Application.Match(ringNo, _
            ws.Range(ws.Cells(2, IND_RINGNO), ws.Cells(lastRow, IND_RINGNO)), 0)
    If Not IsError(found) Then
        FindInIndividuals = CLng(found) + 1  ' +1 because search started at row 2
    End If
End Function

Private Function GetIndividualSex(indRow As Long) As String
    If Not SheetExists(SHT_INDIVIDUALS) Then
        GetIndividualSex = ""
        Exit Function
    End If
    GetIndividualSex = Trim(CStr( _
        ThisWorkbook.Sheets(SHT_INDIVIDUALS).Cells(indRow, IND_SEX).Value))
End Function

Private Function GetIndividualSpecies(indRow As Long) As String
    If Not SheetExists(SHT_INDIVIDUALS) Then
        GetIndividualSpecies = ""
        Exit Function
    End If
    GetIndividualSpecies = Trim(CStr( _
        ThisWorkbook.Sheets(SHT_INDIVIDUALS).Cells(indRow, IND_SPECIES).Value))
End Function

Private Function SheetExists(sheetName As String) As Boolean
    Dim ws As Worksheet
    On Error Resume Next
    Set ws = ThisWorkbook.Sheets(sheetName)
    On Error GoTo 0
    SheetExists = Not (ws Is Nothing)
End Function

' ── Cell formatting helpers ───────────────────────────────────────────────────
Public Sub HighlightCell(cell As Range, isError As Boolean, msg As String)
    With cell
        If isError Then
            .Interior.Color = CLR_ERROR
            .Font.Color = CLR_ERROR_FONT
        Else
            .Interior.Color = CLR_WARN
            .Font.Color = CLR_WARN_FONT
        End If
        .Comment.Delete
        .AddComment msg
        .Comment.Visible = False
    End With
End Sub

Public Sub ClearCell(cell As Range)
    With cell
        .Interior.ColorIndex = xlNone
        .Font.ColorIndex = xlAutomatic
        On Error Resume Next
        .Comment.Delete
        On Error GoTo 0
    End With
End Sub
